services:
  db:
    image: mysql:8.0.28
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: rest_spring_boot_kotlin
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    ports:
      - 3308:3308
    expose:
      - 3308
    networks:
      - spring-kotlin-network
  rest-spring-boot-kotlin:
    image: azevedomax/rest-spring-boot-kotlin
    restart: always
    build: ./rest-springboot-kotlin
    working_dir: /rest-springboot-kotlin
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://db:3308/rest_spring_boot_kotlin?useTimezone=True&serverTimezone=UTC
      SPRING.DATASOURCE.USERNAME: docker
      SPRING.DATASOURCE.PASSWORD: admin123
    ports:
      - 80:80
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - spring-kotlin-network
networks:
  spring-kotlin-network:
    driver: bridge